### ISSUE TITLE
希望build之后的html，还在原来的目录，只是采用不同的后缀，不知道用coolie的话该怎么实现？

### ISSUE THREAD

**Issue by cos800** [cloudcome/nodejs-coolie#2]
我的需求恐怕比较特殊一些，
因为后端框架是我自己写的，而这框架是把html和php按业务模块放在同一个目录里。
类似这样：
![2015-07-03_163028](https://cloud.githubusercontent.com/assets/635184/8495524/dcf2f762-21a0-11e5-8b6a-63c290fc6ae7.png)
（.phtml为模板文件）

并不像传统的PHP框架 把html放在一个目录下，我个人比较喜欢这种结构。

但这种目录结构好像就没办法使用coolie了？

我希望build之后的HTML，还在原来的目录，只是采用不同的后缀，不知道用coolie的话该怎么实现？

**Comment by cloudcome** [comment]
你的需求确实特殊，目前正在着手一种新的配置方式，采用 JS 文件来配置，这样应该可以实现你的需求。敬请关注官方最新信息。

**Comment by cloudcome** [comment]
你这种情况，可以将`.php`文件原样复制（`copy`属性）到目标目录。

**Comment by cos800** [comment]
有道理！
